import React, { useContext } from 'react';
import { withRouter } from 'react-router-dom';

import './Back.css';

import { QuestionsContext } from './../context/Context';

const Back = ({ history }) => {
	const { setIsDisabled } = useContext(QuestionsContext);
	const handleBack = () => {
		history.goBack();
		setIsDisabled(false);
		localStorage.removeItem('deadline');
	};
	return (
		<button className="back-button center" onClick={handleBack}>
			<i className="fa fa-arrow-left"></i>
		</button>
	);
};

export default withRouter(Back);

const questions = [
	{
		Id: 1,
		Ques: 'DDA was established on',
		A: '2034 BS',
		B: '2035 BS',
		C: '2036 BS',
		D: '2037 BS',
		Ans: 'C',
		Setname: '1',
		Wset: '1',
		Subject: 'Forensic Pharmacy',
		Subid: '1',
		Date: '2019/08/24',
	},
	{
		Id: 2,
		Ques: 'Increase in USP designation of suture',
		A: 'Increase in diameter',
		B: 'increase in length',
		C: 'decrease in length',
		D: 'Decrease in diameter',
		Ans: 'D',
		Setname: '2',
		Wset: '1',
		Subject: 'clinical and hospital pharmacy',
		Subid: '1',
		Date: '2019/08/24',
	},

	{
		Id: 3,
		Ques: 'What is the time if any surgical material is steri...',
		A: '15 minutes',
		B: '3 minutes',
		C: '30 minutes',
		D: '10 minutes',
		Ans: 'B',
		Setname: '2',
		Wset: '3',
		Subject: 'clinical and hospital pharmacy',
		Subid: '1',
		Date: '2019/08/24',
	},

	{
		Id: 4,
		Ques: 'Autoclave for gauze sterilization is operated 15 m...',
		A: '110o C',
		B: '125o C',
		C: 'below 100o C',
		D: '121o C ',
		Ans: 'D',
		Setname: '1',
		Wset: '3',
		Subject: 'microbiology',
		Subid: '1',
		Date: '2019/08/24',
	},

	{
		Id: 5,
		Ques: 'In common practice rubber gloves are sterilized by',
		A: 'Hot air',
		B: 'antiseptic rinsing',
		C: 'Autoclave',
		D: 'UV radiation',
		Ans: 'C',
		Setname: '1',
		Wset: '3',
		Subject: 'clinical and hospital pharmacy',
		Subid: '1',
		Date: '2019/08/24',
	},

	{
		Id: 6,
		Ques: 'Teratogenicity is',
		A: 'Acute reaction to drug  ',
		B: 'malformation of foetus',
		C: 'intolerance to drug',
		D: 'tumor formation',
		Ans: 'B',
		Setname: '2',
		Wset: '2',
		Subject: 'clinical and hospital pharmacy',
		Subid: '1',
		Date: '2019/08/24',
	},

	{
		Id: 7,
		Ques: 'Expected well known reaction to a drug resulting i...',
		A: 'Causality',
		B: 'ADR',
		C: 'Side effect',
		D: 'AEFI',
		Ans: 'C',
		Setname: '3',
		Wset: '1',
		Subject: 'clinical and hospital pharmacy',
		Subid: '1',
		Date: '2019/08/24',
	},

	{
		Id: 8,
		Ques: 'Glass vessels & syringes are best sterilized by',
		A: 'Hot air oven',
		B: 'Ethylene oxide',
		C: 'Autoclaving',
		D: 'Irriadiation',
		Ans: 'C',
		Setname: '2',
		Wset: '3',
		Subject: 'clinical and hospital pharmacy',
		Subid: '1',
		Date: '2019/08/24',
	},

	{
		Id: 9,
		Ques: 'Which of the following is incorrect relating to dr...',
		A: 'Maintain integrity of packing',
		B: 'Reduce pilferage & losses',
		C: 'Avoid drug contamination or deterioratio',
		D: 'no need to monitor & record temperature',
		Ans: 'D',
		Setname: '2',
		Wset: '1',
		Subject: 'clinical and hospital pharmacy',
		Subid: '1',
		Date: '2019/08/24',
	},

	{
		Id: 10,
		Ques: 'Promotion of Rational use of drugs is done through',
		A: 'Drug & therapeutic committee ',
		B: 'National list of essential medicines',
		C: 'Standard treatment protocol',
		D: 'All of the above',
		Ans: 'C',
		Setname: '2',
		Wset: '3',
		Subject: 'clinical and hospital pharmacy',
		Subid: '1',
		Date: '2019/08/24',
	},

	{
		Id: 11,
		Ques: 'Indirect consequence (result) of primary action of...',
		A: 'Side effect',
		B: 'ADR',
		C: 'Adverse Effect',
		D: 'Secondary effect',
		Ans: 'D',
		Setname: '2',
		Wset: '2',
		Subject: 'clinical and hospital pharmacy',
		Subid: '1',
		Date: '2019/08/24',
	},

	{
		Id: 12,
		Ques: 'Autoclave for unwrapped item sterilization is oper...',
		A: '15 psi',
		B: '20 psi',
		C: '30 psi',
		D: 'none',
		Ans: 'c',
		Setname: '5',
		Wset: '4',
		Subject: 'clinical and hospital pharmacy',
		Subid: ' 1',
		Date: '2019/08/24',
	},

	{
		Id: 13,
		Ques: 'Drugs are categorized as â€œContraindicatedâ€ on ...',
		A: 'Category X',
		B: 'Category A',
		C: 'Category B',
		D: 'Category D',
		Ans: 'A',
		Setname: '3',
		Wset: '4',
		Subject: 'clinical and hospital pharmacy',
		Subid: '1',
		Date: '2019/08/24',
	},

	{
		Id: 14,
		Ques: 'The extent to which individual patient behavior co...',
		A: 'Patient Compliance',
		B: 'Non-Compliance',
		C: 'Patient counseling',
		D: 'none',
		Ans: 'A',
		Setname: '3',
		Wset: '4',
		Subject: 'clinical and hospital pharmacy',
		Subid: '1',
		Date: '2019/08/24',
	},

	{
		Id: 15,
		Ques: 'In hospital the member secretary of drug & therape...',
		A: 'Nurse',
		B: 'Director',
		C: 'Pharmacist',
		D: 'Doctor',
		Ans: 'C',
		Setname: '5',
		Wset: '4',
		Subject: 'clinical and hospital pharmacy',
		Subid: '1',
		Date: '2019/08/24',
	},

	{
		Id: 16,
		Ques: 'Standard treatment guidelines are',
		A: 'Disease oriented  ',
		B: 'drug oriented  ',
		C: 'both a and b  ',
		D: 'none',
		Ans: 'A',
		Setname: ' 1',
		Wset: '5',
		Subject: 'hospital pharmacy',
		Subid: '1',
		Date: '2019/08/25',
	},

	{
		Id: 17,
		Ques: 'Formulary manual is',
		A: 'Drug oriented   ',
		B: 'patient oriented  ',
		C: 'disease oriented ',
		D: 'all of above',
		Ans: 'A',
		Setname: '2',
		Wset: '3',
		Subject: 'Hospital pharmacy',
		Subid: '1',
		Date: '2019/08/25',
	},

	{
		Id: 18,
		Ques: 'Standard treatment guideline is also called as',
		A: 'Standard treatment schedule',
		B: 'Standard protocols',
		C: 'Therapeutic guidelines',
		D: 'All of the above',
		Ans: 'D',
		Setname: '2',
		Wset: '3',
		Subject: 'Hospital pharmacy',
		Subid: '1',
		Date: '2019/08/25',
	},

	{
		Id: 19,
		Ques: 'Drug Bulletin of Nepal (DBN)  is prepared by',
		A: 'Ministry of health',
		B: 'Department of health service',
		C: 'Department of drug administration',
		D: 'National medicine laboratory',
		Ans: 'C',
		Setname: '3',
		Wset: '4',
		Subject: 'Hospital pharmacy',
		Subid: '1',
		Date: '2019/08/25',
	},

	{
		Id: 20,
		Ques: 'Type of irrational drugs use by prescription',
		A: 'Under prescribing',
		B: 'Extravagant prescribing',
		C: 'Multiple prescribing',
		D: 'All of the above',
		Ans: 'D',
		Setname: '4',
		Wset: '4',
		Subject: 'Hospital pharmacy',
		Subid: '1',
		Date: '2019/08/25',
	},

	{
		Id: 21,
		Ques: 'The rational drug use requires that',
		A: 'Patient receive medicines appropriate to their cli',
		B: 'Cost effectives',
		C: 'Accurate dosing',
		D: 'All of the above',
		Ans: 'D',
		Setname: '5',
		Wset: '5',
		Subject: 'Hospital pharmacy',
		Subid: '1',
		Date: '2019/08/25',
	},

	{
		Id: 22,
		Ques: 'Nepalese national formulary is published by',
		A: 'Department of drug administration',
		B: 'National medicine laboratory',
		C: 'Department of health service',
		D: 'Department of plant resources',
		Ans: 'A',
		Setname: ' 6',
		Wset: '6',
		Subject: 'Hospital pharmacy',
		Subid: '1',
		Date: '2019/08/25',
	},

	{
		Id: 23,
		Ques: 'When was Nepal pharmaceutical association establis...',
		A: '1972AD    ',
		B: '1973AD  ',
		C: '1974AD ',
		D: '1982AD',
		Ans: 'A',
		Setname: '7',
		Wset: '7',
		Subject: 'Hospital pharmacy',
		Subid: '1',
		Date: '2019/08/25',
	},

	{
		Id: 24,
		Ques: 'Pharmacy profession in Nepal was started from',
		A: 'DDA   ',
		B: 'RDRL ',
		C: 'banaspati bibhag  ',
		D: 'DPHS',
		Ans: 'C',
		Setname: '8',
		Wset: '8',
		Subject: 'Hospital pharmacy',
		Subid: '1',
		Date: '2019/08/25',
	},

	{
		Id: 25,
		Ques: 'Certificate level pharmacy course was initiated at...',
		A: '1972AD ',
		B: '1982AD  ',
		C: '1979AD ',
		D: '1973AD',
		Ans: 'A',
		Setname: '9',
		Wset: '9',
		Subject: ' Hospital pharmacy',
		Subid: '1',
		Date: '2019/08/25',
	},
];
